services:

  mysql:
    container_name: mysql
    image: mysql:9.5.0
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_ROOT_PASSWORD}
      MYSQL_USER: ${ENV_MYSQL_USER}
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-volume:/var/lib/mysql

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.4-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db-volume: